### ISSUE TITLE
0.3.0 broke promises for me

### ISSUE THREAD

**Issue by brettjonesdev** [nickb1080/nba#1]
Hey, first off, just wanted to say a huge thanks for your work on this project.  I've used it to build an automatic stats generator for [Pounding The Rock](http://poundingtherock.com) post-game summary posts.  Your node wrapper around the utterly undocumented stats.nba.com endpoints is a lifesaver.  

So I just tried to update from 0.2.0 to 0.3.0, but now I'm getting errors: 
```
[TypeError: Must pass a callback.]
```

This occurs when I use the Promise-style `.then()`:

```javascript
nba.api.scoreboard({ GameDate: moment(date).format('MM/DD/YYYY') }).then(function(resp) {
        /* do stuff */
    });
```

It is important that I be able to use promises, since I have a part of my app in which I make multiple calls and use `Promise.all().then()` to fire my callback after all of the promises have been resolved:

```javascript
Promise.all([nba.api.boxScoreFourFactors(options), nba.api.boxScoreAdvanced(options), nba.api.boxScoreUsage(options), nba.api.playByPlay(options)])
       .then(function(results) { /*do stuff with the 3 response*/ })
```

If you could update so that callback *functions* are not required, that would be great, as I'd love to get up to date with your latest.  

Thanks again for the great project!

**Comment by nickb1080** [comment]
@brettjonesdev I'm going to mark this as closed.

**Comment by brettjonesdev** [comment]
ok, thanks.  One of these days I'll get around to updating and promisify-ing things, but for now I'm just gonna stick with the old version for a little while. :/ Thanks!

**Comment by nickb1080** [comment]
@brettjonesdev take a look at this [gist](https://gist.github.com/nickb1080/c3a1c20fbfee04ddeb9c), I didn't test it but it should overwrite all the API methods with promisified versions. After that you should be able to use it as before, and upgrade with impunity (as long as that code runs before you use `nba.api`).
