### ISSUE TITLE
v1.0.1 currently published on npm

### ISSUE THREAD

**Issue by brandly** [nickb1080/nba#18]
looks like the latest is v1.2.0

since you have that notice about docs being out of date, maybe you're waiting to update those

**Comment by nickb1080** [comment]
1.2.0 is published to npm now. I believe the only significant addition is the `nba.stats.lineups()` method. There have also been some fixes to how the `nba.usePromsies()` method is applied.

**Comment by brandly** [comment]
thanks Nick!

**Comment by nickb1080** [comment]
@brandly out of curiosity, are you using this in a project?

**Comment by brandly** [comment]
a week ago, i started to put together a small chat bot that could pull NBA stats into a conversation. the published version of this repo didn't seem to be working the way i expected, but i saw you were making major changes, so i figured i'd wait for those.

i was writing it for [hubot](https://hubot.github.com/), so it'll probably end up on github. i'll try to let you know!

**Comment by nickb1080** [comment]
That sounds awesome. Yeah, I've been working on this in fits and starts over the last couple months, but trying to avoid breaking changes. If anything seems screwy or unexpected, don't hesitate to open an issue!

**Comment by brandly** [comment]
Hey Nick! I wrote [a tiny chat bot](https://github.com/brandly/jim/blob/master/scripts/nba.coffee) that delivers player and team averages, as well as today's game scores. It's written as a Hubot plugin, so I should break it out into its own repo, but for now, it's with the bot.

For game scores, I used an endpoint I found on an nba.com dashboard, and it's working well, but I'd prefer to leverage your repo if I can. Is there any way to get current scores or nba schedule data? I'd like to get data like "what were Steph Curry's stats last night?" but I'm not sure how to go about it.

Thanks for this repo. I really appreciate it!

**Comment by nickb1080** [comment]
For completed games you can use the `playerProfile` endpoint as so:

```
var nba = require("nba");

module.exports = function recentStats (name) {
  var id = nba.playerIdFromName(name);

  if (id == null) {
    throw new Error("no player named " + name + " found");
  }

  nba.stats.playerProfile({playerId: id}, function (err, data) {
    // data.gameLogs is an array of the 10 most recent games. Each item is shaped like:
    
    // {
    //   "playerId": 201939,
    //   "gameId": "0021500548",
    //   "gameDate": "JAN 08, 2016",
    //   "matchup": "GSW @ POR",
    //   "wl": "W",
    //   "min": 29,
    //   "fgm": 8,
    //   "fga": 18,
    //   "fgPct": 0.444,
    //   "fG3M": 4,
    //   "fG3A": 11,
    //   "fg3Pct": 0.364,
    //   "ftm": 6,
    //   "fta": 6,
    //   "ftPct": 1,
    //   "oreb": 0,
    //   "dreb": 3,
    //   "reb": 3,
    //   "ast": 9,
    //   "stl": 1,
    //   "blk": 0,
    //   "tov": 1,
    //   "pf": 2,
    //   "pts": 26,
    //   "plusMinus": 22
    // }

  });

}
```

I'm pretty sure one the `boxScore` endpoints can get games in progress. The problem is building a list of `gameIds` for a season, which I'm going to try shortly.

**Comment by nickb1080** [comment]
Pulled schedules back to 2005 and put them here https://github.com/nickb1080/nba-schedules, will package it through npm soon.

**Comment by brandly** [comment]
Thanks again! `playerProfile` is working great. I haven't changed any code to use `nba-schedules` yet, but I think it'll provide more flexibility
