### ISSUE TITLE
Broken API end point : playerDashPtShotLog

### ISSUE THREAD

**Issue by wardhanster** [nickb1080/nba#20]
Hi, 
Today a few hours earlier I noticed nba.stats.playerDashPtShotLog, was no longer functional ; On further investigation, I found that the url is not returning any JSON data.

(URL I used)
http://stats.nba.com/stats/playerdashptshotlog?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&Period=0&PlayerID=200826&Season=2015-16&SeasonSegment=&SeasonType=Regular+Season&TeamID=0&VsConference=&VsDivision=

This makes me think the url has been removed or the API end point has been deprecated/removed
Could you point me to the new API end point having the same results of the above, I tried to find it on the stats.nba.com with no luck.

Regards

**Comment by nickb1080** [comment]
Hi, yes it seems like both `playerDashPtReboundLogs` and `playerDashPtShotLog` are no longer being served by NBA. Both methods are removed in 2.0.0.
