### ISSUE TITLE
Endpoint documentation from nba_py

### ISSUE THREAD

**Issue by nickb1080** [nickb1080/nba#22]
Add a script to pull this in automatically https://github.com/seemethere/nba_py/wiki/stats.nba.com-Endpoint-Documentation

Per https://github.com/seemethere/nba_py/issues/18, consider generating API client programmatically from a machine-readable documentation file.

**Comment by danielwelch** [comment]
I'm working on doing this [here](https://github.com/danielwelch/little-pynny) as a fun weekend project. Using the endpoint documentation from nba_py, I'm working on generating a JSON documentation file that adheres to the [Swagger specification](http://swagger.io/specification/). I initially created a JSON simply containing the endpoints and parameters and used it to generate a simple, very low-level client, but then thought using something like Swagger would be more useful. 

So far, other than reformatting the information, I've specified whether or not each parameter is required, per the 400 responses from the stats.nba.com API, and identified endpoints from the documentation file that appear to be inactive (404). 

This is a very rough first pass on this, and I have not tested or validated this representation at all (aside from validating that the code generates a valid swagger specification). 

Next, I'd like to add information about what the API expects for each parameter. Hoping to do this by inspecting responses further (ex: in some cases, if a bad parameter is used, the API will return a regex that the parameter must match).

**Comment by nickb1080** [comment]
developed package [nba-client-template](https://github.com/nickb1080/nba/pull/26) which will be used in (forthcoming) [version 3]( https://github.com/nickb1080/nba-client-template)] of this package
