### ISSUE TITLE
Season ID

### ISSUE THREAD

**Issue by carty64** [nickb1080/nba#23]
https://github.com/nickb1080/nba/blob/movement/test/integration/stats.js#L153

You weren't sure about the season ID. If you go to data.nba.com, it lists `season_id: 12015`

**Comment by nickb1080** [comment]
Nice catch, thanks!

**Comment by ngxiaoyi** [comment]
@nickb1080 awesome project! Is it free to use this library to create a web application? I mean what about the copyrights of these stats,  do they have some limitations about the nba official stats, sportVU & synergy data while using this to create an app or software?

**Comment by nickb1080** [comment]
I've not been able to find any copyright or licensing agreement that either explicitly allows or prohibits the use of these statistics. In general, my sense is that the NBA (or some developers there) are aware that their API endpoints are being used by third party libraries and applications, but they have elected to do nothing about it so far. It's also sort of hard to tell if things like sports statistics are even subject to copyright -- a quick Google search tells me they [probably aren't](http://www.law360.com/articles/8470/sports-stats-not-protected-by-copyright-judge).

But, I'm not a lawyer.
