### ISSUE TITLE
SportVu data

### ISSUE THREAD

**Issue by ben-pr-p** [nickb1080/nba#24]
I noticed you mentioned the format of the SportVu data was a bit odd, but you have you been able to get it at all? It seems as if one the NBA's endpoint, `/stats/locations_getmoments` may have been removed, since https://www.npmjs.com/package/nba-movement no longer works (neither does the Python equivalent: http://savvastjortjoglou.com/nba-play-by-play-movements.html).

Any idea if this data is still available / when were you last able to access it?

**Comment by nickb1080** [comment]
The wording the NBA uses about what "sport vu" is is sort of confusing. In this package I refer to sport vu data as coming from endpoints that have `sportvu` in the URL. These stats are mostly aggregations of play-by-play movement data, not the movement data itself. Basically [these endpoints](https://github.com/nickb1080/nba/blob/master/src/sport-vu-endpoints.js). 

The actual movement data seemed to only be available for a short period of time. I haven't accessed successfully in several months. My educated guess is that [the providers](http://www.stats.com/sportvu/sportvu-basketball-media/) of this very expensive data were less than pleased with  the blog posts showing how to harvest this data straight from the NBA's website and asked them to remove it.

**Comment by ben-pr-p** [comment]
I share your educated guess. Oh well!
