### ISSUE TITLE
Any idea if the NBA will open up playerdashboardbygeneralsplits ??

### ISSUE THREAD

**Issue by anditburns** [nickb1080/nba#25]

**Comment by nickb1080** [comment]
Where'd you get this endpoint from? Can you send me a URL on stats.nba.com where they make a request to it?

**Comment by anditburns** [comment]
http://stats.nba.com/player/#!/203076/stats/ underlying this url is a API call:

http://stats.nba.com/stats/playerdashboardbygeneralsplits?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerID=203076&PlusMinus=N&Rank=N&Season=2015-16&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&VsConference=&VsDivision=

**Comment by anditburns** [comment]
this has been pretty handy:
https://github.com/danielwelch/little-pynny. I've used his swaggon.json file on my own site to document some of the endpoints.

**Comment by nickb1080** [comment]
Huh! Interesting. Not sure how they are detecting when to respond with `Access Denied`. Copying as cURL command from Chrome and then executing it from the command line works fine. But using an HTTP API client like Postman from the same cURL command fails, even with the referer and user-agent headers set correctly. No idea how to get around the 403 unfortunately 😕
