### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by briancbarrow** [nickb1080/nba#29]
When using the playerSplits method I get the following:
`You don't have permission to access "http://stats.nba.com/stats/playerdashboardbygeneralsplits?" on this server.`

Have they changed something and we can't access it now?

**Comment by nickb1080** [comment]
Hmm, what version of this library are you using? A while back the NBA started requiring some headers, so I added that at some point. If you are using a version from before headers were being set, you might see this error.

I've run the tests and the `playerSplits` method seems to work for me on latest (3.2.0).

**Comment by briancbarrow** [comment]
That is the version I am using. So I am still learning to code and wanted to use this in a capstone project for my bootcamp. I have used it inside of a React application. Right now I am just console logging the data and it has worked with some of the other methods. This is the code I have so far, maybe I'm doing something wrong.
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import './index.css';

const nba = require('nba')

nba.stats.playerSplits({
  Season: "2015-16",
  SeasonType: "Regular Season",
  LeagueID: "00",
  PlayerID: "201566",
  MeasureType: "Base",
  PerMode: "PerGame",
  PlusMinus: "N",
  PaceAdjust: "N",
  Rank: "N",
  Outcome: "",
  Location: "",
  Month: "0",
  SeasonSegment: "",
  DateFrom: "",
  DateTo: "",
  OpponentTeamID: "0",
  VsConference: "",
  VsDivision: "",
  GameSegment: "",
  Period: "0",
  LastNGames: "0"
})
.then(data => console.log(data))
```

**Comment by brandly** [comment]
i just ran that block of code, leaving out the import statements up top, and it worked fine! i'm currently on nodejs `v5.3.0`, with this `nba` repo at `v3.2.0`.

you can run `npm install nba@latest` to make sure you have the latest version of this project installed.

good luck!

**Comment by nickb1080** [comment]
Ah! I think this is likely a browser vs. Node.js issue. I just tried `make browser-test` (basically, runs the same integration tests used in the Node.js test suite but in a browser context) and it seems to crap out on `playerSplits` (and also `scoreboard`). I'm almost certain it's to do with the `referrer` header, which we [can't set](http://stackoverflow.com/questions/3350778/modify-http-headers-for-a-jsonp-request) on JSONP requests. Basically, any endpoints the NBA locks down by `referrer` are not going to work from the browser. I'm going to close this issue, I've opened #30 as a reminder to myself to surface this better to users.

**Comment by briancbarrow** [comment]
Forgive me for being ignorant as I am still learning, but how would I set it up using Node.js?

**Comment by brandly** [comment]
> how to make the data accessible to my application?

@briancbarrow you could build your own server as a proxy to stats.nba.com

in that situation, your React app would app requests to a server you made. that server would make requests using this `nba` package, before delivering them to your app.

using [express](http://expressjs.com/), that might look like this:

```js
const express = require('express')
const nba = require('nba')
const app = express()

app.get('/playerSplits', (req, res) => {
  nba.stats.playerSplits(req.query)
  .then(data => {
    res.send(data)
  }, error => {
    res.status(400).send(error)
  })
})

app.listen(3000, function () {
  console.log('Ready')
})
```

then, in your React app, instead of using this `nba` package, make requests to this small server instead. if you ran this locally, you'd make a GET request to `localhost:3000/playerSplits`, passing any options for `nba.stats.playerSplits` in through the query string.

disclaimer: i didn't run this code, but hopefully it helps explain how this might work 😅

**Comment by briancbarrow** [comment]
Thanks @brandly I will try that when I get home tonight. That makes sense now and I should be able to get it working.

**Comment by nickb1080** [comment]
Alternately, you can render pages on the server with React:

```js
const express = require('express')
const nba = require('nba')
const app = express()
const React = require("react");
const ReactDOMServer = require("react-dom/server");
const SpiffyPlayerSplitsView = require("./PlayerSplits.jsx");

app.get('/playerSplits', (req, res) => {
  nba.stats.playerSplits(req.query)
  .then(data => {
    const html = ReactDOMServer.renderToString(
        <SpiffyPlayerSplitsView data={data}/>
    );
    res.send(html);
  }, error => {
    res.status(400).send(error)
  })
})

app.listen(3000, function () {
  console.log('Ready')
})
```
