### ISSUE TITLE
teamPlayerDashboard return 400 with right parameter

### ISSUE THREAD

**Issue by florianpnn** [nickb1080/nba#33]
Hi there, when trying to use the `teamPlayerDashboard` endpoint I encounter a 400 bad request throwing `The field TeamID must be between 1 and 2147483647`. No matter the `teamID` I use I get the same response.

Here is my call
```
nba.stats.teamPlayerDashboard({
  teamID: 1610612749,
  SeasonType: "Regular Season"
}).then(function(data) {
  fs.writeFile('team-player-dashboard.json', JSON.stringify(data, null, 2), function(err) {
    if (err) throw err
    console.log('team-player-dashboard.json saved!')
  })
}).catch(function(err) {
  console.log(err)
})
```

**Comment by brandly** [comment]
this [this test](https://github.com/nickb1080/nba/blob/master/test/integration/stats.js#L64) failing on your end?

**Comment by brandly** [comment]
oh! you're supplying a `teamId` but not a `TeamId`.

**Comment by florianpnn** [comment]
@brandly oh, good catch! Working now!

**Comment by nickb1080** [comment]
Yeah urgh... I've gone back and forth several times on how to handle parameter capitalization. On the one hand, it's simpler to just use the capitalization the NBA wants. On the other hand, it's not idiomatic in JS. One solution might be a util that can translate them intelligently -- previously the keys were upper cases automatically which seemed to confuse people. So an opt-in util probably would be best

**Comment by nickb1080** [comment]
*upper-CASED

**Comment by nickb1080** [comment]
A better solution would be to c
