### ISSUE TITLE
Slow stats.nba endpoints

### ISSUE THREAD

**Issue by djchie** [nickb1080/nba#35]
It seems like the endpoints to `stats.nba` are slow. I tried making a request directly to the stats.nba API and the same thing happened. It all takes about 8~10 seconds to run.

What's interesting is that if I make a request from Postman rather than localhost, the speed is just fine.

I was wondering if I was running into a DNS lookup issue, so I curled with the following:

`
curl --trace-time -w "time_namelookup: %{time_namelookup}\ntime_connect: %{time_connect}\ntime_appconnect: %{time_appconnect}\ntime_pretransfer: %{time_pretransfer}\ntime_redirect: %{time_redirect}\ntime_starttransfer: %{time_starttransfer}\n----------\ntime_total: %{time_total}\n" -v http://stats.nba.com/stats/scoreboardV2?DayOffset=0&LeagueID=00&gameDate=12/25/2016
`

And got this as the result:

```
time_namelookup:  0.013
time_connect:  0.038
time_appconnect:  0.000
time_pretransfer:  0.038
time_redirect:  0.000
time_starttransfer:  9.077
----------
time_total:  9.078
```

Both the time_starttransfer and the ttfb from the Chrome console seems to indicate that it's something on their end?

What I'm wondering is if you're experiencing this as well?

**Comment by nickb1080** [comment]
Yeah, running the integration tests it seems like the stats endpoints are all super slow for me as well -- all taking 8+ seconds to complete. I just saw your note on `nba_py` – seems like the same issue.

When trying your curl I noticed it returned a 403 (missing some headers I think), I was wondering if they were slowing down requests like that. I tried another which is 200-ing for me as of now, with same long delay: 

`curl --trace-time -w "time_namelookup: %{time_namelookup}\ntime_connect: %{time_connect}\ntime_appconnect: %{time_appconnect}\ntime_pretransfer: %{time_pretransfer}\ntime_redirect: %{time_redirect}\ntime_starttransfer: %{time_starttransfer}\n----------\ntime_total: %{time_total}\n" -v http://stats.nba.com/stats/playerprofilev2\?PlayerID\=201939\&LeagueID\=00\&PerMode\=PerGame`

**Comment by nickb1080** [comment]
@djchie can you try on latest (3.2.3)? After a little detective work, it seems like adding `Connection: keep-alive` header solves this issue!

**Comment by nickb1080** [comment]
Hmm... on [Travis](https://travis-ci.org/nickb1080/nba/jobs/199425094) I'm still seeing these requests take a long time. Perhaps there was some kind of caching that sped this up. Not quite sure what's going on here...

**Comment by nickb1080** [comment]
@djchie Here's your time tracing with the headers postman is sending (using Chrome's "Copy as cURL" tool in DevTools)

```
curl --trace-time -w "\ntime_namelookup: %{time_namelookup}\ntime_connect: %{time_connect}\ntime_appconnect: %{time_appconnect}\ntime_pretransfer: %{time_pretransfer}\ntime_redirect: %{time_redirect}\ntime_starttransfer: %{time_starttransfer}\n----------\ntime_total: %{time_total}\n" -v 'http://stats.nba.com/stats/playerprofilev2?PlayerID=201939&LeagueID=00&PerMode=PerGame' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Postman/4.4.2 Chrome/51.0.2704.103 Electron/1.2.5 Safari/537.36' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Connection: keep-alive' -H 'Postman-Token: 81a358aa-8cec-516f-8d61-2034628209d1' --compressed
```

**Comment by nickb1080** [comment]
I'm going to close this -- the running time of the test suite seems to be similar to what it was a couple months ago, and I no longer see response time clustering around 8-10s.

**Comment by djchie** [comment]
Sorry for the long wait in reply. Just wanted to confirm that I did try it out with the headers you provided and it's faster now. Thanks!
