### ISSUE TITLE
Capitalization on Query Params

### ISSUE THREAD

**Issue by calesce** [nickb1080/nba#5]
Hey Nick,

I was messing around with some of the API methods, and I noticed some behavior where the parameters had to be lower case for them to override the defaults. 

Here's an example in express, using the correct key, 'Season':
```
router.get('/', function(req, res) {
  nba.ready(function() {
    nba.api.playersInfo({ Season: "2010-11"}, function(err, data) {
      res.send(data);
    });
  });
});
```

This would result in the request:
```
{ LeagueID: '00', Season: '2014-15', IsOnlyCurrentSeason: '1', season: '2010-11' }
```

However, if I changed the key to 'season', the request would work properly, and I would get the players for the 2010-11 season:

```
{ LeagueID: '00', Season: '2010-11', IsOnlyCurrentSeason: '1' }
```

I know this has something to do with the ```twoWayMap``` function and it should work regardless of capitalization. I'm not sure yet how all of the utility functions work and how they transform the parameters, but when I get some time to dig in I'll hopefully be able to figure it out and make a PR.

**Comment by nickb1080** [comment]
Yeah you're on the right track. I'm not sure exactly what the issue is, but the main problem is that all the utility functions and stuff are completely untested. If I get some time this week I'm going to try to write tests to specify how they *should* work and see where it goes wonky.

**Comment by calesce** [comment]
Gotcha, now that I looked a little more, it seems that it just translates upper camel case to lower (and vice-versa). I just assumed upper would work because of the defaults you were using in ```endpoints.js```.

I'll take a stab at writing some tests for ```utils.js``` and other parts of the library, partially because I need to get better at writing tests, and partially because I did get some other types of weird errors on the endpoints I added.

**Comment by nickb1080** [comment]
Sounds good! Let me know if you run into any roadblocks

**Comment by nickb1080** [comment]
For anyone who sees this in the future:

For all options passed to methods in this module, I've tried to ensure they are in camel case as is usual for JavaScript projects. This helps avoid having to constantly refer to the inconsistent capitalization scheme that the NBA uses. The translation table is in https://github.com/nickb1080/nba/blob/master/src/dicts.js
