### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by winnemucca** [nickb1080/nba#9]
I am installing with npm install and also tried with sudo npm install.  Keep getting cannot read property o of undefined

**Comment by nickb1080** [comment]
At first glance it looks like an error is coming back from NBA. Could be that the API is no longer public. I'll try to investigate further when I have a moment.

```
{"Message":"An error has occurred."}
```

**Comment by nickb1080** [comment]
@winnemucca after a quick test, the NBA's API still looks to be generally available. There is an issue with the build script that gets new data -- the endpoint that it receives from may have changed. This whole library needs a good 4-8 hours of work to make it usable, sorry for the inconvenience.

**Comment by nickb1080** [comment]
@winnemucca whoops that was an easier fix than I thought. I must've moved some stuff around and forgotten to run the build scripts. Version 0.3.1 on NPM should be good to go.
